### ISSUE TITLE
Not seeing new S3 node steps with zip installed to libext

### ISSUE THREAD

**Issue by fellenberger** [rundeck-plugins/powershell-aws-s3-steps#2]
Same as Create / Delete sandbox, I'm not seeing the new steps available after installing the zip.

In addition, I must point out that the custom aws S3 steps I provided as reference prior to starting this project are defined as "RemoteScriptNodeStep" whereas the steps defined in this project are of type  "WorkflowNodeStep".  What is the impact of this difference?

[plugin.txt](https://github.com/rundeck-plugins/powershell-aws-s3-steps/files/1692384/plugin.txt)

**Comment by miguelantonio** [comment]
Hi @fellenberger we are doing the change to RemoteScriptNodeStep
