### ISSUE TITLE
Software requirements for using this plugin?

### ISSUE THREAD

**Issue by fellenberger** [rundeck-plugins/powershell-aws-s3-steps#4]
In reviewing the code in this plugin, looks like you are checking for the availability of a module called "AWSPowerShell".  It doesn't look like this module is available even after installing the standard "awscli64.msi" distributed by AWS.

Please advise on the current pre-req requirements, and we may want to discuss the opportunity to use the "aws-cli", as installed by the msi.

Also want to make sure it is abundantly clear that we intend on using this plugin for more than AWS - S3 interaction.

Today, we use an internal Object Store implementation by Cleversafe, which is "S3 compatible", and its's working well with our Linux aws-s3 Rundeck plugin, which uses basic "> aws s3" calls utilizing the standard aws-cli package command-line utility.

Manual run of the checks you are performing in plugin code (won't currently pass):

```
PS C:\Users\runx_oisadm> Get-Module -listavailable -Name "AWSPowerShell"
PS C:\Users\runx_oisadm> Import-Module AWSPowerShell
Import-Module : The specified module 'AWSPowerShell' was not loaded because no valid module file was found in any
module directory.
At line:1 char:1
+ Import-Module AWSPowerShell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (AWSPowerShell:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by miguelantonio** [comment]
Hi @fellenberger 
I added a requirements session on the README:
https://github.com/rundeck-plugins/powershell-aws-s3-steps#requirements

You need to install the module, for example using `Install-Module -Name AWSPowerShell`

**Comment by fellenberger** [comment]
@miguelantonio I will readily admit that Powershell is not my cup of tea.  Can it be any more non-intuitive?  :)

It doesn't seem like Install-Module is a valid command for this version of powershell.  Looks like v4.0?

I've attached a screenshot and would greatly appreciate any guidance you can offer to get pre-reqs addressed so I can test this plugin..

![ps_install_issue](https://user-images.githubusercontent.com/10405889/35878369-f3855a1a-0b2c-11e8-99ca-9370c6a53c5d.png)

![ps_version](https://user-images.githubusercontent.com/10405889/35878504-50932f70-0b2d-11e8-9b51-966283876489.png)

**Comment by fellenberger** [comment]
taking a look at the links provided in the readme.  thanks and stay tuned

**Comment by fellenberger** [comment]
Downloading the SDK and will try to install.  In reviewing the requirements for running the SDK, its seems an AWS account is required, and this seems all too very AWS - S3 centric.  

The original goal was to be able to utilize the aws-cli commands (aws s3 ls|cp|mv|rm|sync) just as they are being done on Linux (as provided in the aws plugin I provided at onset of this engagement).

I will continue to walk this path of installing the SDK and see where it gets us, but giving you the heads up that we may quickly run into obstacles if there are corporate policy violations in installing the SDK, or if this implementation that uses the SDK is not compatible with our internal object store (Cleversafe).

This may result in the need to re-work the plugin to make native "aws s3 [command]" calls.  Including the full source of the "s3 cp" plugin step we are using in Linux, for reference.

```
#!/bin/bash
# s3-cp
set -eu

(( $# != 3 )) && {
   echo >&2 "usage: $0 S3Endpoint source destination"
   exit 2
}

#
# RDSO-223: if file check option enabled, exit if file check fails
#
if [ "${RD_CONFIG_CHECKEXEC:-}" == true ]; then
   if [ ! -f ${RD_CONFIG_FILEEXISTS:-} ]; then
      echo "Filechecker: Did not find ${RD_CONFIG_FILEEXISTS}. Skipping execution."
      exit 0
   else
      echo "Filechecker: Found ${RD_CONFIG_FILEEXISTS}. Continuing execution."
   fi
fi

S3Endpoint=$1
SOURCE=$2
DESTINATION=$3

CLOPTS=()
[[ "${RD_CONFIG_QUIET:-}" == true ]] && CLOPTS=(${CLOPTS[*]:-} --quiet)
[[ "${RD_CONFIG_RECURSIVE:-}" == true ]] && CLOPTS=(${CLOPTS[*]:-} --recursive)
[[ "${RD_CONFIG_DRYRUN:-}" == true ]] && CLOPTS=(${CLOPTS[*]:-} --dryrun)
[[ "${RD_CONFIG_INCLUDE:-}" == true ]] && CLOPTS=(${CLOPTS[*]:-} $RD_CONFIG_INCLUDE)
[[ "${RD_CONFIG_EXCLUDE:-}" == true ]] && CLOPTS=(${CLOPTS[*]:-} $RD_CONFIG_EXCLUDE)
[[ "${RD_CONFIG_OPTIONS:-}" == true ]] && CLOPTS=(${CLOPTS[*]:-} $RD_CONFIG_OPTIONS)


[[ -n "${RD_CONFIG_ACCESS_KEY:-}" ]]        && export AWS_ACCESS_KEY_ID=${RD_CONFIG_ACCESS_KEY}
[[ -n "${RD_CONFIG_SECRET_ACCESS_KEY:-}" ]] && export AWS_SECRET_ACCESS_KEY=${RD_CONFIG_SECRET_ACCESS_KEY}
[[ -n "${RD_CONFIG_DEFAULT_REGION:-}" ]]    && export AWS_DEFAULT_REGION=${RD_CONFIG_DEFAULT_REGION}

if [ -n "${RD_OPTION_ALTERNATE_AWSCLI_PATH:-}" ]; then
   if [ -f ${RD_OPTION_ALTERNATE_AWSCLI_PATH:-}/aws ]; then
      echo "Alternate awscli path (${RD_OPTION_ALTERNATE_AWSCLI_PATH:-}) looks to be valid.  Will attempt to use ${RD_OPTION_ALTERNATE_AWSCLI_PATH:-}/aws for OOSS/S3 interaction."
      export PATH=${RD_OPTION_ALTERNATE_AWSCLI_PATH:-}:$PATH
   else
   	  echo "WARNING: Alternate awscli path (${RD_OPTION_ALTERNATE_AWSCLI_PATH:-}) not found!  Doing nothing..."
   fi
fi

# RDSO-234: Implement retry strategy on fail
for (( i=0; i<=${RD_CONFIG_RETRIES:-}; i++))
do
   #aws s3 cp "$SOURCE" "$DESTINATION" ${CLOPTS[*]:-}
   aws --endpoint-url=$S3Endpoint s3 cp "$SOURCE" "$DESTINATION" ${CLOPTS[*]:-}

   if [ "$?" -gt "0" ]; then
      echo "WARNING: Object Store failure detected. Retrying..."
   else
      break #success
   fi
done

exit $?
# Done
```

**Comment by fellenberger** [comment]
Ran the SDK installer and purposely isolated what was to be installed to *just* the "AWS Tools for Powershell".

![aws_sdk_install_options](https://user-images.githubusercontent.com/10405889/35880127-e67865ec-0b31-11e8-86a3-c166b0413e28.png)

After install, still not seeing any results from running:

Get-Module -listavailable -Name "AWSPowerShell"

Conversely, I did install the aws-cli .msi as we have done on other Windows boxes, and I do have access to the "aws s3 [command]" interfaces. 

![aws-cli](https://user-images.githubusercontent.com/10405889/35880233-3e761a8c-0b32-11e8-8d5e-286ec2e03d50.png)

**Comment by fellenberger** [comment]
Becuase this specific box is under our administration (not all boxes will be), I then installed the SDK with all options enabled.  After doing this, still don't get any results with the "Get-Module" command check.

![get-module](https://user-images.githubusercontent.com/10405889/35880351-8e621924-0b32-11e8-8b47-f1b311ce915b.png)

**Comment by fellenberger** [comment]
Then tried the following as your code would attempt:

> Import-Module AWSPowerShell

But results of that were not successful either.

![import-module](https://user-images.githubusercontent.com/10405889/35880555-18907ca8-0b33-11e8-91fc-bd60a045d800.png)

**Comment by miguelantonio** [comment]
Hi @fellenberger could you try doing the full installation of the SDK installer, not just specifics? I just re-tried this and works like a charm that way

**Comment by fellenberger** [comment]
Please see my prior comments.  I tried this with all packages enabled.  Same result.

**Comment by fellenberger** [comment]
In addition, "Install-Module" command will not work.  It's not a valid command in Powershell v4.x apparently?

**Comment by fellenberger** [comment]
Looks like an existing powershell console doesn't pick up the fact that new modules were installed... I opened up a new powershell console, and I am now seeing the AWSPowerShell module available, so that is great.

![awspowershell](https://user-images.githubusercontent.com/10405889/35886405-c854def6-0b45-11e8-847b-9fd88e8592eb.png)

I will proceed with some initial testing and let you know how it goes.
